import { OhVueIcon, addIcons } from 'oh-vue-icons'
import {
  FaHome,
  FaThLarge,
  FaBook,
  FaCamera,
  FaChartBar,
  FaPrint,
  FaCog,
  FaChevronRight,
  FaChevronLeft,
  FaSpinner,
  FaList,
  FaStar,
  FaDollarSign,
  FaSearch,
  FaPlus,
  FaDownload,
  FaTrash,
  FaTimes,
  FaImage,
  FaPencilAlt,
  FaStop,
  FaSun,
  FaArrowsAlt,
  FaMobileAlt,
  FaDatabase,
  FaFileExport,
  FaFileImport,
  FaExclamationTriangle,
  FaCheck,
} from 'oh-vue-icons/icons'

export default defineNuxtPlugin((nuxtApp) => {
  addIcons(
    FaHome,
    FaThLarge,
    FaBook,
    FaCamera,
    FaChartBar,
    FaPrint,
    FaCog,
    FaChevronRight,
    FaChevronLeft,
    FaSpinner,
    FaList,
    FaStar,
    FaDollarSign,
    FaSearch,
    FaPlus,
    FaDownload,
    FaTrash,
    FaTimes,
    FaImage,
    FaPencilAlt,
    FaStop,
    FaSun,
    FaArrowsAlt,
    FaMobileAlt,
    FaDatabase,
    FaFileExport,
    FaFileImport,
    FaExclamationTriangle,
    FaCheck,
  )
  nuxtApp.vueApp.component('VIcon', OhVueIcon)
})
